apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-east-2

nodeGroups:
  - name: chep-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: 
     publicKeyname: eks-course
