apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: 
     publicKeyname: eks-course

  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
     publicKeyname: eks-course
